### ISSUE TITLE
`class` property was broken, like pug`div( class="container" )`

### ISSUE THREAD

**Issue by shirohana** [pugjs/babel-plugin-transform-react-pug#111]
As title, seems the `class` property alias was broken since `^7.0.0` but works in `^6.0.0`.

It seems like the [removal of alias `class -> className`](https://github.com/pugjs/babel-plugin-transform-react-pug/pull/62/files#diff-851638e5b5aa807ff4f27d8cdac589ca) in #62?

##### `src/visitors/Tag.js`
```diff
+// TODO: Need to drop all aliases for attributes
 switch (name) {
   case 'for':
     name = 'htmlFor';
     break;
   case 'maxlength':
     name = 'maxLength';
     break;
-  case 'class':
-    name = 'className';
-    break;
 }
```

---

Here's the sample:

#### It works when using `className` \([REPL](https://react.pugjs.org/repl#%7B"code":"Ly8gaW1wb3J0ICQgZnJvbSAnLi9zdHlsZS5jc3MnCmNvbnN0ICQgPSB7IC8qIGFzIENTU01vZHVsZSAqLyB9CgpleHBvcnQgZnVuY3Rpb24gTGluayAoKSB7CiAgcmV0dXJuIHB1Z2AKICAgIGRpdiggY2xhc3NOYW1lPSQuQ29udGFpbmVyICkKICAgICAgYSggY2xhc3NOYW1lPVskLkxpbmssICQuTGlua0FjdGl2ZV0gKQogIGAKfQ=="%7D)\)
```js
// import $ from './style.css'
const $ = { /* as CSSModule */ }

export function Link () {
  return pug`
    div( className=$.Container )
      a( className=[$.Link, $.LinkActive] )
  `
}
```

#### And it broken when `class` but it should be work \([REPL](https://react.pugjs.org/repl#%7B%22code%22:%22Ly8gaW1wb3J0ICQgZnJvbSAnLi9zdHlsZS5jc3MnCmNvbnN0ICQgPSB7IC8qIGFzIENTU01vZHVsZSAqLyB9CgpleHBvcnQgZnVuY3Rpb24gTGluayAoKSB7CiAgcmV0dXJuIHB1Z2AKICAgIGRpdiggY2xhc3M9JC5Db250YWluZXIgKQogICAgICBhKCBjbGFzcz1bJC5MaW5rLCAkLkxpbmtBY3RpdmVdICkKICBgCn0=%22%7D)\)
```js
// import $ from './style.css'
const $ = { /* as CSSModule */ }

export function Link () {
  return pug`
    div( class=$.Container )
      a( class=[$.Link, $.LinkActive] )
  `
}
```

#### Full log from my console
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /Users/shirohana/Repositories/react-spa-template/src/components/dev-tools/sitemap.js:41
    39|   return pug`
    40|     div( class=$.Container )
  > 41|       a( class=[$.Link, $.LinkActive] )
    42|   `
    43| }
    44|

We can't use expressions in shorthands, use "className" instead of "class"
    at makeError (/Users/shirohana/Repositories/react-spa-template/node_modules/pug-error/index.js:32:13)
    at Context.error (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/context.js:63:34)
    at node.attrs.map (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/visitors/Tag.js:81:23)
    at Array.map (<anonymous>)
    at getAttributes (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/visitors/Tag.js:45:28)
    at getAttributesAndChildren (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/visitors/Tag.js:125:17)
    at Object.jsx (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/visitors/Tag.js:166:35)
    at visitJsx (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/visitors.js:82:20)
    at nodes.forEach (/Users/shirohana/Repositories/react-spa-template/node_modules/babel-plugin-transform-react-pug/dist/visitors.js:58:19)
    at Array.forEach (<anonymous>)
```

**Comment by ezhlobo** [comment]
@shirohana my intention was to avoid own aliases and just pass everything what we have to jsx. With `class` it's tricky since jsx didn't allow us to use it and now it throws warning, but it works well there. Maybe we should consider adding an alias for `class` attribute.

Do you prefer using `class` just because it's shorter or you have other reasons?

**Comment by shirohana** [comment]
It it surprised me that the `class` has been removed without documented (´・ω・｀)

The `class` should keep be available just because we love Pug more than JSX, and `class` is *a Syntax of Pug*, not an alias.

Just because we can use Pug as our *preprocessor of JSX*, we can avoid some *bad design* of JSX, like ugly optional rendering condition, ugly array iteration, meaningless closing-tag, and so many reasons that drive us to find a better workaround, that is why this plugin be existed.

**Comment by shirohana** [comment]
We're looking for a **solution**, not another JSX-like alternatives. (´・ω・｀ʃ♡ƪ)

**Comment by shirohana** [comment]
Is it any plan for this (´・ω・｀)？

**Comment by billypon** [comment]
@ezhlobo Could you give us an option that we can map `class` to `className`, default is not map? I prefer using `class`. Passthrough everything is right, because `class` and `id` are just html 
attributes. But map `class` to `className` also is right, it can be a syntax of pug, and it's shorter. We are writing pug, not jsx, when we use this plugin.

**Comment by ezhlobo** [comment]
@shirohana @billypon hey ✋, I feel sad that I made you waiting for too long. 

I thought a bit about that and now I tend to agree that we need to have a map between `class` and `className`. I'll check it out tomorrow or after that. 

Also, the message like `We can't use expressions in shorthands, use "className" instead of "class"` points to an issue in the logic, nothing about the avoidance of aliases.

**Comment by quantpioneer** [comment]
@ezhlobo In case you want to add the `class -> className` mapping back, then wouldn't it also make sense to add mapping for [all other CSS attributes](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes)?

**Comment by shirohana** [comment]
@JeanPaulvB These [all other CSS attributes](https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes) were created for JSX that makes almost DOM Element Attributes to be a valid JS Identifier (like variable names), but Pug is just a HTML-preprocessor, no need to be compatible with JavaScript, as I think (´・ω・｀)

**Comment by quantpioneer** [comment]
@shirohana But the PUG attributes do need to be compatible with React right? Hence a pure Pug to JSX mapping (like `class` to `className`) could be very nice.

**Comment by shirohana** [comment]
@JeanPaulvB Yeah that is what I expect this plugin does \:D

✅I'd like that do:
```pug
.container
  label( for="email" )
  input#email( type="text" )
```

❌but not:
```pug
.container
  label( html-for="email" )
  input#email( type="text" )
```

❌and never:
```pug
.container
  label( htmlFor="email" )
  input#email( type="text" )
```

this plugin done that pretty well in this example, and I hope it can also applies on `class` -> `className` ❤️

**Comment by danielnarey** [comment]
Any plans to revert to allowing “class” (as in Pug language spec) in place of “className” (as in JS/JSX)?

**Comment by shirohana** [comment]
Hi,
I'm back here for React and frontend ヾ(\*´ω｀\*)ノ

Currently I have a plan to make a new option to allow using:

- `` pug`div.box` ``,
- `` pug`div( class="box" )` ``,
- `` pug`div( className="box" )` `` and
- `` pug`div( class=styles.box )` `` (for CSS Module)

in same time, just like alias that works well before.

with options like:

##### `babel.config.js`
```json
{
  "plugins": [
    ["transform-react-pug", {
      "attributeAlias": {
        "KEY": "VALUE",
      }
    }]
  ]
}
```

Which:

- `KEY`: Attribute name of HTML Element which is invalid in JSX and listed in [React Doc](https://reactjs.org/docs/dom-elements.html#differences-in-attributes).

    For example:
    - `"class"` replaced by className
    - `"for"` replaced by htmlFor

- `VALUE`: The replacement string that should be valid in JSX.

This way provides the most flexibility of use cases, you can setup for JSX-like syntax, Pug-like syntax, and even more power that Pug doesn't have:

#### JSX-like

```js
"attributeAlias": {
  /* No need to configure, unlisted attributes will be fallback as it is */
}

pug`div( className="box" )` // valid
pug`div( class="box" )` // invalid

pug`label( htmlFor="username" )` // valid
pug`label( for="username" )` // invalid
```

### Pug-like

```js
"attributeAlias": {
  "class": "className",
  "for": "htmlFor"
}

pug`div( className="box" )` // valid
pug`div( class="box" )` // valid, will be parsed to JSX `<div className="box"></div>`

pug`label( htmlFor="username" )` // valid
pug`label( for="username" )` // valid, will be parsed to JSX `<label htmlFor="username"></label>`
```

### More power

```js
"attributeAlias": {
  "@click": "onClick",
  "@change": "onChange",
  "@html": "dangerouslySetInnerHTML"
}

pug`button( @click=handleClick )` // valid, will be parsed to JSX `<button onClick=handleClick></button>`
pug`svg( @html=canvas )` // valid, will be parsed to JSX `<svg dangerouslySetInnerHTML=canvas></svg>`
```

Default alias will be like that for compatible with nature syntax of Pug:

```json
"attributeAlias": {
  "class": "className",
  "for": "htmlFor"
}
```
---

I'll try to implement in few days, hope that can match everyone's preference easily.

Welcome for any advice ٩(｡・ω・｡)

**Comment by p-98** [comment]
@shirohana @ezhlobo Are there any updates or reasons why the PR is not merged?

**Comment by shirohana** [comment]
@p-98 I have no idea, guessing this project was been deprecated with no announcements. and I'm gone for poor type checking from pug months ago 😉
